export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className='grid justify-center h-screen items-center bg-teal mx-8'>
        {children}
   
      </body>
    </html>
  );
}
