'use client';
import React, { useState } from 'react';
import { usePathname } from 'next/navigation';

import '@/app/globals.css';
import { Navbar } from 'components/shared/navbar/Navbar';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function ProtectedLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [variantNavBar, setVariantNavBar] = useState('primary');
  const pathname = usePathname();
  React.useEffect(() => {
    if (pathname.includes('voting') || pathname.includes('details')) {
      setVariantNavBar('secondary');
    } else {
      setVariantNavBar('primary');
    }
  });

  return (
    <div className="w-full flex flex-col justify-between h-screen">
      {children}

      <footer className="fixed bottom-6 container px-8">
        <Navbar variant={variantNavBar} />
      </footer>
    </div>
  );
}
