import { Navbar } from 'components/shared/navbar/Navbar';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className='grid justify-center items-center h-screen bg-teal'>
        {children}
        <footer>
        </footer>
      </body>
    </html>
  );
}
