import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    //A root layout is the top-most layout in the root app directory. It is used to define the <html> and <body> tags
    //https://nextjs.org/docs/app/api-reference/file-conventions/layout
    <html lang="en">
      <body className="grid h-screen items-center">
        {/* justify-center breaks the layout for results */}
        {children}
      </body>
    </html>
  );
}
