export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section className="px-8 py-10 bg-yellow h-[667px]">
      <h1 className="title-black mb-1">Poll Details</h1>
      {children}
    </section>
  );
}
